version: 0.2
phases:
  install:
    commands:
      - dotnet tool install -g Amazon.Lambda.Tools

  pre_build:
    commands:
      - echo Restore started on `date`
      - cd AWSCURManager
      - dotnet clean
      - dotnet restore
      
  build:
    commands:
      - echo Build started on `date`
      - dotnet lambda package-ci --configuration Release --framework netcoreapp3.1 --s3-bucket $BUCKET --template AWSCURManager.template --output-template bin/Release/netcoreapp3.1/$PROJECT_NAME.template --output-package bin/Release/netcoreapp3.1/$PROJECT_NAME.zip

artifacts:
  name: BuildOutput
  files:
    - AWSCURManager/bin/Release/netcoreapp3.1/$PROJECT_NAME.template
  discard-paths: yes  